name: deploy-expiration

# To run when a PR is merged to master and the expiration file is change
on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t roblkdeboer/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push roblkdeboer/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Get connection credentials to reach into DO k8s cluster
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # Restart expiration service
      - run: kubectl rollout restart deployment expiration-depl
