name: deploy-manifests

# To run when a PR is merged to master and the auth file is change
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Get connection credentials to reach into DO k8s cluster
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # Apply all new config files to our cluster
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
