# This is a workflow to trigger executing automated testing

name: tests-payments

# Run this workflow whenever a PR is created and the files changed are in the payments directory
on:
  pull_request:
    paths:
      - 'payments/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
